# Estructuras de datos en ![](https://www.r-project.org/Rlogo.png)



## Matrices (matrix)

Las matrices son arrays de dos dimensiones, los cuales contienen elementos del mismo tipo.
Se organizan en filas y columnas.

La manera más simple de crear una matriz es utilizando la función `matrix(data, nrow, ncol,  byrow)`.

 + `data`: vector con los valores de la matriz.
 + `nrow`: número de filas deseadas.
 + `ncol`: número de columnas deseadas.
 + `byrow`: define si la matriz se llena por filas o por columnas.

Igual que en los vectores, podremos dar nombres tanto a las filas como a las columnas con  las funciones `rownames(m)` y `colnames(m)`, respectivamente.

### Creación de matrices

In [1]:
###################################
# Matrices: Creación              #
###################################

m1 <- matrix(1:9, byrow = TRUE, nrow = 3)
m1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [2]:
m2 <- matrix(c(0, -1, 4)) # Crea una matriz con una columna
m2

[,1]
[1,]  0  
[2,] -1  
[3,]  4

In [3]:
d1 <- diag(3) # Crea una matriz diagonal 3x3
d1

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [4]:
d2 <- diag(c(1, 2, 3)) # Crea una matriz diagonal y asigna el vector como diagonal
d2

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [5]:
t_m1 <- t(m1) # Traspuesta de m1
e <- eigen(m1) # Lista con autovalores y autovectores
d <- det(m1) # Determinante de la matriz

### Operaciones sobre matrices

Podemos realizar operaciones aritméticas con matrices (sumas, restas, multiplicaciones…)
de manera similar a como hemos hecho con los vectores.

In [8]:
###################################
# Matrices: Operaciones           #
###################################

a_matrix <- matrix(1:9, byrow = TRUE, nrow = 3)
b_matrix <- matrix(11:19, byrow = TRUE, nrow = 3)

total_matrix <- a_matrix + b_matrix
total_matrix

[,1] [,2] [,3]
[1,] 12   14   16  
[2,] 18   20   22  
[3,] 24   26   28

Igual que hicimos con los vectores, podemos realizar la misma operación sobre todos los  elementos de la matriz. En este caso, R creará una matriz auxiliar con las mismas  dimensiones que la matriz original.

In [9]:
total_matrix <- a_matrix + 2
total_matrix

[,1] [,2] [,3]
[1,] 3     4    5  
[2,] 6     7    8  
[3,] 9    10   11

También aplicaremos funciones a una matriz. Por ejemplo: `rowSums(m); colSums(m); rowMeans(m); colMeans(m)`

In [10]:
rowSums(total_matrix)
colMeans(total_matrix)
max(total_matrix)

[1] 12 21 30

[1] 6 7 8

[1] 11

### Manipulación de matrices

Para añadir columnas a una matriz se utiliza la función `cbind(m1, m2, …)`, la cual une
matrices y/o vectores por columna.

In [11]:
###################################
# Matrices: Manipulación          #
###################################

# Unión de matrices por columnas
big_matrix_2 <- cbind(a_matrix, b_matrix)
big_matrix_2

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    11   12   13  
[2,] 4    5    6    14   15   16  
[3,] 7    8    9    17   18   19

In [12]:
# Unión de matriz y vector por columnas
big_matrix_2 <- cbind(big_matrix_2, c(1, 5, 6))
big_matrix_2

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    2    3    11   12   13   1   
[2,] 4    5    6    14   15   16   5   
[3,] 7    8    9    17   18   19   6

Para añadir filas a una matriz se utiliza la función `rbind(m1, m2, …)`, la cual une matrices y/o  vectores por fila.

In [13]:
# Unión de matrices por filas
big_matrix_1 <- rbind(a_matrix, b_matrix)
big_matrix_1

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 11   12   13  
[5,] 14   15   16  
[6,] 17   18   19

In [14]:
# Unión de matriz y vector por filas
big_matrix_1 <- rbind(big_matrix_1, c(1, 5, 6))
big_matrix_1

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 11   12   13  
[5,] 14   15   16  
[6,] 17   18   19  
[7,]  1    5    6

### Indexación de matrices

Al igual que en los vectores, utilizaremos los corchetes `[ ]` para indexar matrices. En el caso  particular de las matrices usaremos dos números enteros: uno para la fila y otro para la  columna `[row, column]`.

Para seleccionar todos los elementos de una fila o una columna, basta con no incluir ningún  número antes o después de la coma, respectivamente. Por ejemplo: `matrix[row, ]`; `matrix[, col]`.

In [16]:
###################################
# Matrices: Indexación            #
###################################
m <- matrix(1:9, byrow = TRUE, nrow = 3)

# Indexando con números positivos
m[1, ] # Seleccionamos la primera fila
m[1:2, ] # Seleccionamos las dos primeras filas
m[, ncol(m)] # Seleccionamos la última columna
m[, c(1, ncol(m))] # Seleccionamos la primera y la última columna
m[1, ] <- 0 # Asigna un vector de ceros a la primera fila

[1] 1 2 3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[1] 3 6 9

[,1] [,2]
[1,] 1    3   
[2,] 4    6   
[3,] 7    9

In [17]:
# Indexando con números negativos
m[-1, ] # Seleccionamos todas las filas menos la primera
m[-nrow(m), -ncol(m)] # Quitamos la última fila y la última columna

[,1] [,2] [,3]
[1,] 4    5    6   
[2,] 7    8    9

[,1] [,2]
[1,] 0    0   
[2,] 4    5

In [18]:
# Indexando con vectores lógicos o expresiones booleanas
m_selection <- matrix(c(TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE), byrow = TRUE, nrow = 3)
m[m_selection] # Seleccionamos en función de una matriz de booleanos
m[m > 7] # Todos los > 7
m[m == 0] # Todos los 0

[1] 0 4 7 0 6 9

[1] 8 9

[1] 0 0 0

In [ ]:
# Indexando por nombre
colnames(m) <- c("c1", "c2", "c3")
rownames(m) <- c("r1", "r2", "r3")
m[, c("c1", "c3")] # Selección de columnas por nombre
m[c("r2", "r3"), c("c1", "c2")] # Selección de filas y columnas por nombre

### Información sobre matrices

![info_mat](imgs/02_01.png)

## Arrays (array)

Para crear un array de más de dos dimensiones utilizaremos la función: `array(data, dim)`:
+ `data`: vector con los valores que tendrá el array.
+ `dim`: vector con las dimensiones del array.

Los vectores y las matrices son casos especiales de arrays. Los vectores con una dimensión  y las matrices con dos.

In [19]:
###################################
# Arrays: Creación                #
###################################

a <- array(1:8, dim=c(2, 2, 2))
a

m <- array(1:9, dim=c(3, 3))
m

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

## Ejercicio 3

In [21]:
###################################
# Matrices                        #
###################################

# Los siguientes vectores contienen la recaudación de las tres primeras películas de Star Wars en US y fuera de US (non-US)
new_hope <- c(461, 314.4)
empire_strikes <- c(290.5, 247.9)
return_jedi <- c(309.3, 165.8)

In [22]:
# Crea una matriz que contenga toda la información (con tres filas)
star_wars_matrix <- matrix(c(new_hope, empire_strikes, return_jedi), byrow=TRUE, nrow=3)

In [23]:
# Ponles nombres a las columnas: "US" y "non-US"
colnames(star_wars_matrix) <- c("US", "non-US")

In [24]:
# Ponles nombres a las filas: "A New Hope", "The Empire Strikes Back" y "Return of the Jedi"
rownames(star_wars_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

In [25]:
# Si el precio de la entrada es de 5$, estima el número de espectadores de cada película
visitors <- star_wars_matrix / 5

In [26]:
# Como el precio de las entradas no es el mismo todos los años, creamos una matriz de precios
ticket_prices_matrix <- matrix(c(5, 5, 6, 6, 7, 7), nrow = 3, byrow = TRUE, dimnames = list(rownames(star_wars_matrix), colnames(star_wars_matrix)))

In [27]:
# Repite el cálculo del número de espectadores con la matriz anterior
visitors <- star_wars_matrix / ticket_prices_matrix

In [28]:
# Calcula el numero de espectadores medio en US
average_us_visitors <- mean(visitors[, 1])

In [29]:
# Calcula el numero de espectadores medio fuera de US
average_non_us_visitors <- mean(visitors[, 2])

In [30]:
# Calcula los totales de recaudación por película
worldwide_vector <- rowSums(star_wars_matrix)

In [31]:
# Añade el vector anterior con los totales por película como una nueva columna de la matriz
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)

In [32]:
# Crea una nueva matriz con las recaudaciones de las siguientes tres películas de Star Wars
phantom_menace <- c(474.5, 552.5)

In [33]:
# Crea una nueva matriz con las recaudaciones de las siguientes tres películas de Star Wars
phantom_menace <- c(474.5, 552.5)
attack_clones <- c(310.7, 338.7)
revenge_sith <- c(380.3, 468.5)
star_wars_matrix2 <- matrix(c(phantom_menace, attack_clones, revenge_sith), byrow=TRUE, nrow=3)

In [34]:
# Ponles nombres a las columnas: "US" y "non-US"
colnames(star_wars_matrix2) <- c("US", "non-US")

In [35]:
# Ponles nombres a las filas: "The Phantom Menace", "Attack of the Clones" y "Revenge of the Sith"
rownames(star_wars_matrix2) <- c("The Phantom Menace", "Attack of the Clones", "Revenge of the Sith")

In [36]:
# Une en una nueva matriz la recaudación de todas las películas, las tres primeras filas corresponderán
# a las tres primeras películas y las tres siguientes a las últimas películas
all_wars_matrix <- rbind(star_wars_matrix, star_wars_matrix2)

In [37]:
# Calcula los totales de recaudación de todas las películas en US y fuera de US
total_revenue_vector <- colSums(all_wars_matrix)

In [38]:
# Calcula la media recaudada de las tres primeras películas fuera de US
non_us_all <- mean(star_wars_matrix[, 2])

In [39]:
# Calcula la media recaudada de las 2 primeras películas fuera de US
non_us_some <- mean(star_wars_matrix[1:2, 2])