# Estructuras de datos en ![](https://www.r-project.org/Rlogo.png)



## Listas (list)

Una lista es una colección de diferentes tipos de objetos. Las listas también son conocidas
como vectores recursivos.

Estos objetos pueden ser:
+ Vectores atómicos.
+ Matrices.
+ Data frames.
+ Otras listas (cada una de las cuales puede tener una profundidad distinta).

Cada elemento de la lista puede ser de un tipo diferente, no tienen porque ser objetos de la  misma clase.

Al igual que en los vectores los índices de la lista van desde 1 hasta su longitud, `length(l)`.

## Creación de listas

In [9]:
###################################
# Listas: Creación                #
###################################

my_vector <- 1:10 
my_matrix <- matrix(1:9, ncol = 3)
my_df <- mtcars[1:10,]

In [10]:
# Creación de lista sin nombre
l1 <- list(my_vector, my_matrix, my_df)
l1

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

In [11]:
# Creación de lista con nombre
l2 <- list(vec = my_vector, mat = my_matrix, df = my_df)
l2

$vec
 [1]  1  2  3  4  5  6  7  8  9 10

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

In [ ]:
# Utilizando al función de composición
l3 <- c(l1, l2)
l3

## Operaciones sobre listas

Análisis exploratorio de los datos de una lista:
+ `head(l)`: devuelve los primeros elementos de la lista.
+ `tail(l)`: devuelve los últimos elementos de la lista.
+ `str(l)`: muestra de forma rápida la estructura de la lista. Funciona de manera similar a los data frames.

In [12]:
###################################
# Listas: Operaciones             #
###################################

str(l2)
head(l2, 2)
tail(l2, 2)

List of 3
 $ vec: int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ mat: int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ df :'data.frame':	10 obs. of  11 variables:
  ..$ mpg : num [1:10] 21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2
  ..$ cyl : num [1:10] 6 6 4 6 8 6 8 4 4 6
  ..$ disp: num [1:10] 160 160 108 258 360 ...
  ..$ hp  : num [1:10] 110 110 93 110 175 105 245 62 95 123
  ..$ drat: num [1:10] 3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92
  ..$ wt  : num [1:10] 2.62 2.88 2.32 3.21 3.44 ...
  ..$ qsec: num [1:10] 16.5 17 18.6 19.4 17 ...
  ..$ vs  : num [1:10] 0 0 1 1 0 1 0 1 1 1
  ..$ am  : num [1:10] 1 1 1 0 0 0 0 0 0 0
  ..$ gear: num [1:10] 4 4 4 3 3 3 3 4 4 4
  ..$ carb: num [1:10] 4 4 1 1 2 1 4 2 2 4


$vec
 [1]  1  2  3  4  5  6  7  8  9 10

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

In [13]:
append(l1, list(my_vector), 2) #Añadimos un vector en la posición 2
l1

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[4]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

In [14]:
l2[[2]] <- NULL #Eliminamos el elemento de la posición 2
l2

$vec
 [1]  1  2  3  4  5  6  7  8  9 10

$df
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

No es posible realizar operaciones aritméticas sobre los elementos de una lista.

En algunas ocasiones puede resultar útil simplificar una lista, convirtiéndola en un vector
atómico. Para ello utilizamos la función `unlist(l)`.

## Indexación de listas

Para indexar los elementos de una lista utilizaremos normalmente dobles corchetes `[[ ]]`.  También es posible utilizar corchetes simples `[ ]` el igual que en los vectores atómicos. La  diferencia entre las dos operaciones radica en el tipo de objeto que devuelve la selección:
+ Con **dobles corchetes** obtendremos un objeto de la clase del elemento ubicado en dicha  posición.
+ Con **corchetes simples R** devolverá una lista con el objeto ubicado en dicha posición.

También se puede utilizar el **operador** `$` para obtener el mismo resultado que con los dobles  corchetes.

Cuando se trabaja con listas, la mayoría de las veces emplearemos dobles corchetes `[[ ]]` o
`$`, evitando utilizar corchetes simples `[ ]`.

Por lo demás, la selección de elementos funciona como en el resto de objetos de R que  hemos visto hasta ahora.

In [15]:
###################################
# Listas: Indexación              #
###################################

# Selección por índice
l2[2] #Devuelve una lista
l2[[2]] #Devuelve una matriz

$df
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230          22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280          19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4

In [16]:
class(l2[2])
class(l2[[2]])

[1] "list"

[1] "data.frame"

In [17]:
# Selección por nombre
l2[["mat"]] #Devuelve una matriz
l2$"mat" #Devuelve una matriz
l2["mat"] # Devuelve una lista

NULL

NULL

$<NA>
NULL


In [18]:
l2[["mat"]][1, ] #Selecciona la primera fila de la matriz
l2[["vec"]][3] #Selecciona el tercer elmento del vector

NULL

[1] 3

## Información sobre listas

![info_list](imgs/05_01.png)

## Ejercicio 6

In [19]:
###################################
# Listas                          #
###################################

actors <- c("Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers", "Barry Nelson")
scores <- c(4.5, 4.0, 5.0)
sources <- c("IMDb1", "IMDb2", "IMDb3")
comments <- c("Best Horror Film I Have Ever Seen", "A truly brilliant and scary film from Stanley Kubrick", "A masterpiece of psychological horror")
reviews <- data.frame(scores, sources, comments)

# Crea una lista que contenga los siguientes componentes:
#   1. moviename: "The Shining"
#   2. actors: el vector de actores
#   3. reviews: el data frame de revbiews
shining_list <- list(moviename = "The Shining", actors = actors, reviews = reviews)

# Selecciona el último actor del vector de actores de la lista
last_actor <- shining_list[["actors"]][5]

# Selecciona la segunda de las críticas del data frame de reviews de la lista
second_review <- shining_list[["reviews"]][2, ]

# Añade un nuevo elemento a lista:
#   1. year: 1980
shining_list_full <- c(shining_list, year = 1980)

# Comprueba el contenido de la lista empleando la función str
str(shining_list_full)

List of 4
 $ moviename: chr "The Shining"
 $ actors   : chr [1:5] "Jack Nicholson" "Shelley Duvall" "Danny Lloyd" "Scatman Crothers" ...
 $ reviews  :'data.frame':	3 obs. of  3 variables:
  ..$ scores  : num [1:3] 4.5 4 5
  ..$ sources : Factor w/ 3 levels "IMDb1","IMDb2",..: 1 2 3
  ..$ comments: Factor w/ 3 levels "A masterpiece of psychological horror",..: 3 2 1
 $ year     : num 1980


## Resumen de objetos en R

![info_list](imgs/05_02.png)